# Generated by Django 5.2.5 on 2025-09-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
